### ISSUE TITLE
FR: when a revision has been reviewed, avoid reviewing again.

### ISSUE THREAD

**Issue by xinbenlv** [google/wikiloop-battlefield#114]

**Comment by hrasyid** [comment]
any pointer on how to tackle this, @xinbenlv ? I agree this is a little annoying, for small wikis it will get repetitive after a while. It should especially avoid picking a revision that has been reviewed by the very same user.

**Comment by xinbenlv** [comment]
Temp fixed by https://github.com/google/wikiloop-battlefield/issues/114
