### ISSUE TITLE
Why appear "NaN" on http://battlefield.wikiloop.org/marked

### ISSUE THREAD

**Issue by d2513850** [google/wikiloop-battlefield#121]
Why appear "NaN" on http://battlefield.wikiloop.org/marked

**Comment by xinbenlv** [comment]
You are right, this is a bug. I will fix it soon

**Comment by aligoren** [comment]
@xinbenlv I found why is this shows nan.

Time string shows NaN because of this code piece. `new Date(this.revision.timestamp).toString()`

**Comment by xinbenlv** [comment]
> I'll fix it if I can get an wiki key :)
What's a wiki key? Happy to provide

**Comment by aligoren** [comment]
Okay, I'm deploying now. Btw, I meant I didn't see any data when I run it my locale. I thought this was about MediaWiki consumer key :)

**Comment by xinbenlv** [comment]
It's not. The reason it has zero data is because a new Heroku Review App
will also create a new MongoDB instance, which is completely empty.
