### ISSUE TITLE
The decision UI should not jump around

### ISSUE THREAD

**Issue by vrandezo** [google/wikiloop-battlefield#124]
Currently, the decision UI (the buttons saying "Looks good" / "Don't know" / "Should be reverted" / "Next") jumps around, and is positioned depending on the length of the diff, and whether there is the table showing me my decision.

I would prefer if these buttons were always on the same location, i.e. move them above the diff, so I don't have to scroll and position the mouse in both directions again and again.

**Comment by xinbenlv** [comment]
Thank you, this is a great idea.

**Comment by xinbenlv** [comment]
Temporarily solve by changing the order, and change the style
