### ISSUE TITLE
Chinese translation issue

### ISSUE THREAD

**Issue by ChenKB91** [google/wikiloop-battlefield#125]
In nuxt.config.js, line 125: `DiffNotAvailable: "该页面的版本差异暂时无法读取，可以重试。有时被涂鸦的版本可能被完全删除，您可以查看页面历史。"`
Should be "该页面的版本差异暂时无法读取，可以嘗試重新載入。有时被破壞的版本可能被完全删除，您可以查看页面历史。"
"涂鸦" means graffiti in Chinese.

**Comment by xinbenlv** [comment]
Thank you for suggesting. I have updated the translation with your version. If you want to update other part of the translation, feel free to let me know at anytime! 

Also if you are familiar with Github, please feel absolutely free to send Pull Request. I will approve and pick asap. (and you become recognized as a contributor :p )

Thank you @ChenKB91
