### ISSUE TITLE
Undefined userGaId in Contributions URL

### ISSUE THREAD

**Issue by aligoren** [google/wikiloop-battlefield#128]
Hi, I found a bug. There is a bug in Contributions URL. `$cookiez.get ('_ ga')` returns undefined.

## Example URL:

`domain.tld/marked/?userGaId=undefined`

Will it always have a cookie id? If no, I think Contributions URL should be hidden when ga id is undefined.

![image](https://user-images.githubusercontent.com/4205423/71077590-c6117580-2198-11ea-830c-6b8febc83bb7.png)

## Line of Related File

https://github.com/google/wikiloop-battlefield/blob/08fe661a5827f46661a1ae937a8366df431583b4/layouts/default.vue#L61

**Comment by xinbenlv** [comment]
We are considering merging the `UserGaId` with `WikiUserName`, see #61 

When a user logged in with MediaWiki Oauth, we will have their `WikiUserName`,, if not, we will use the cookie id related to a session generated by Google Analytics

**Comment by aligoren** [comment]
Okay, I understand. I'll try to fix the `undefined` thing. Thanks.

**Comment by xinbenlv** [comment]
Great, thank you!

**Comment by xinbenlv** [comment]
This was fixed
