### ISSUE TITLE
Add URLs that will default to a specific language

### ISSUE THREAD

**Issue by hrasyid** [google/wikiloop-battlefield#135]
e.g. http://battlefield.wikiloop.org/id that defaults to Indonesian, http://battlefield.wikiloop.org/de that defaults to German, etc.

Will improve access to non-English users because you don't have to teach them how to change the language.

**Comment by xinbenlv** [comment]
+1, we need to discuss the design of such URL: whether it's better to be a URL `path` or a `parameter`?

**Comment by hrasyid** [comment]
My vote is to use path like  http://battlefield.wikiloop.org/de, which will make it easier to remember/share for people who want to work in a specific language. But I'm fine either way.

**Comment by xinbenlv** [comment]
It now works as proposed by @hrasyid
