### ISSUE TITLE
Can't change language from mobile

### ISSUE THREAD

**Issue by hrasyid** [google/wikiloop-battlefield#139]
When using the website from a mobile browser, the navigation bar is collapsed, including the language selector. However, when the navbar is opened, tapping on the language selector collapse the navbar immediately before you have a chance to change the language.

**Comment by xinbenlv** [comment]
I could make the change in iOS of my iPhone 8P. Can you help us reproduce it by revealing your hardware spec?

**Comment by hrasyid** [comment]
I was using Chrome in pixel 3. 
If it helps, I can also reproduce in desktop if I emulate a device using Chrome developer tools

**Comment by dz-s** [comment]
@xinbenlv @hrasyid pretty sure we could close this issue after some people test/be ok with the results.

**Comment by xinbenlv** [comment]
@dz-s thank you, yes!
