### ISSUE TITLE
Leaderboard Needs a Pagination

### ISSUE THREAD

**Issue by wisn** [google/wikiloop-battlefield#144]
Displaying hundreds of records in a single page is kinda heavy. Moreover, from the mobile user perspective, it is tiring to scroll the page down. I believe that we need to add pagination on this page.

**Comment by xinbenlv** [comment]
Thank you, @wisn,

Agreed.

Users mostly only care about the following two things
1. Who among all, ranks the best, so usually top 10 or top50 will be good.
2. How far do {I, my friends, my wiki community) rank, so it makes sense to display only a few nearest to users
We need a better design of leaderboard. Do you want to join the discussion. Let me open a new issue.

**Comment by xinbenlv** [comment]
this is fixed now.
