### ISSUE TITLE
Localize the generated edit summary when reverting

### ISSUE THREAD

**Issue by hrasyid** [google/wikiloop-battlefield#151]
The automatically generated edit summary when reverting is currently always in English ("Identified as test/vandalism using [[:m:WikiLoop Battlefield]](version ${version}). See it or provide your opinion")

Code:
https://github.com/google/wikiloop-battlefield/blob/38d3e349a59c064eb187524bbe53713df3119f0b/components/RevisionCard.vue#L370

It would be nice if this string can be localized, because this edit summary will be visible to other people in the reviewed Wikipedia, and these people might not read English or might prefer not seeing edit summaries in English.

**Comment by jeffreykeefer** [comment]
This has been working, but suddenly this evening is no longer present when seeking to revert. There is no summary of it available in the last several I tried. It just goes to the diff page.

**Comment by hrasyid** [comment]
@jeffreykeefer  It's still working for me. Could you check the history if the last few edits are from the same user? The tool has a known behavior (intentional) of linking to the history page (rather than the revert page) if it is the case, see #143

**Comment by xinbenlv** [comment]
Since the discussion is still live between @hrasyid and @jeffreykeefer , I am re-opening this issue

**Comment by jeffreykeefer** [comment]
It seems to be working again as it was, so whatever the tweaks, they seem to be holding. Thanks.

**Comment by hrasyid** [comment]
Thanks for confirming. I highly suspect you ran into #143, which indeed causes something like you described in a subset of cases
