### ISSUE TITLE
FR: Make auto-gen avatar representative of all users

### ISSUE THREAD

**Issue by wiki-user** [google/wikiloop-battlefield#162]
I noticed that the system automatically generates avatars for all users using the __male__ sprites from the [dicebear avatars](https://avatars.dicebear.com/), these were added in eb6667505c01d476ef3d151b1c5dcb51ce697ea4. While this is useful in graphically identifying users, I think in its current form it is somewhat problematic, since these avatars do not represent all possible users of the tool.

I'd propose one of the following two solutions:

1. Switch to the [human sprites of the same theme](https://www.npmjs.com/package/@dicebear/avatars-human-sprites), these sprites combine both female and male avatars to create a more complete representation. This still has the downside that the gender of the generated avatar will often not correspond to the gender of the user.
2. Switch to one of the more abstract avatar packs, for example [identicons](https://www.npmjs.com/package/@dicebear/avatars-identicon-sprites) or [robot like avatars](https://www.npmjs.com/package/@dicebear/avatars-bottts-sprites). I think this is the best solution, since it avoids unnecessarily gendering your users in their avatar. This way you can not get the gender wrong, also for people who identify as non-binary.

I hope you will take this issue into consideration, please let me know what you think :)

**Comment by xinbenlv** [comment]
@wiki-user thank you, that's wonderful. I actually have the same question with you. I asked this question to dicebear and didn't get a response. At the time only male was available. Now that you point to me there are other options, I am going to switch to them, thank you!

**Comment by xinbenlv** [comment]
@wiki-user DiceBear new version and human/identicon/robot still not working, filed https://github.com/DiceBear/avatars/issues/49

I will switch immediately when there is a good alternative. Stay tuned

**Comment by FlorianKoerner** [comment]
> I asked this question to dicebear and didn't get a response.

We are very sorry, if we missed a question. What exactly is the question?

It is important that always the same versions are used for @dicebear/avatars and the sprite collections.

Also note the slightly modified API since version 4.0.0

**Comment by xinbenlv** [comment]
> We are very sorry, if we missed a question. What exactly is the question?

@FlorianKoerner thank you for joining the discussion. I remember a while ago (5month~ish) when I first add avatar, I asked somewhere I couldn't find about DiceBear at the time did not support both men and women in its random avatar.

>Also note the slightly modified API since version 4.0.0

Oh, ok let me try

**Comment by FlorianKoerner** [comment]
I remember. Then a new collection called "human" was added. See: 
https://github.com/DiceBear/avatars/issues/31

I had made a merge request for the code adjustments. See: #165

**Comment by xinbenlv** [comment]
Closed by #165
