### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by jeffreykeefer** [google/wikiloop-battlefield#171]
Receiving an Internal Server Error when trying to log on after I click Allow on the OAuth page. Cannot log in.

**Comment by xinbenlv** [comment]
Hi @jeffreykeefer, thank you for reporting it, I will check on them.

Just one thing, are you using our **production** deployment which is the link of "http://battlefield.wikiloop.org"? We do have other deployments too, but just in case.

**Comment by xinbenlv** [comment]
I have no problem login, could you help me get more details?

**Comment by jeffreykeefer** [comment]
It is working now; may have just been a temporary thing . . . that is the url I ordinarily use for this.

**Comment by xinbenlv** [comment]
@jeffreykeefer yeah, that's right. I fixed it with a quick solution and a full solution is in planning too. But hope it helps~ Thank you!
