### ISSUE TITLE
FR: Consider identify anonymous users with IP address, same as Wikipedia

### ISSUE THREAD

**Issue by xinbenlv** [google/wikiloop-battlefield#194]

**Comment by hrasyid** [comment]
Please also consider whether this is a good idea privacy-wise.. IP address can be used to look up rough locations for example. Even in wikipedia it comes with warnings to ensure user is aware of this.

**Comment by xinbenlv** [comment]
Em... You are right.. initially I think this will be same as Wikipedia and we do warn people. After you remind me, and a second thought, I think IP address will be a bit sensitive. We probably need a strong reason before we could proceed with this route. I will now close this issue and revisit when the first time we got vandalism from anonymous user.

**Comment by xinbenlv** [comment]
Closed as indefinitely tabled.
