### ISSUE TITLE
Bug: revert open a page on wikipedia but when I click publish nothing is done!

### ISSUE THREAD

**Issue by doplu** [google/wikiloop-battlefield#238]
Hello,
I have tested wikiloop-battlefield in english and in french before (a few weeks) and it was working fine when I clicked on "Revert" : it oppenned the correct url on wikipedia (english or french) and I could revert. ;)
Now, when I open the wikipedia url for a revert, (the edit summary looks fine : "Identified as test/vandalism using [[:m:WikiLoop Battlefield]] version 4.0.1-beta. See it or provide your opinion at http://battlefield.wikiloop.org/revision/enwiki/XXXXXXX ). I click on publish and it load the normal article. Then I manually check if the changes were made, and none was made (and it is not because someone has done the change before me!).

I may have an idea why ? Since a few weeks I use (in english and french wikipedia) the option "Automatically enable all new beta features". In your opinion could it be the cause of the problem ?

Thanks in advance ;)

**Comment by xinbenlv** [comment]
Can you try it a few more times. A common case when I encountered this is because when your reverting conflicts with another edits. If after trying a few more you can replicate this, could you kindly record a screen video and upload here?

**Comment by doplu** [comment]
Hello,
As requested here is a video (sorry for the first 30 seconds) I just did for wikipedia english : https://gofile.io/d/IMQyLa
Url of the edit: https://en.wikipedia.org/w/index.php?title=Storming_of_the_Bastille&oldid=956088587
I had the same bug with the french wikipedia.
Thanks in advance ;)

**Comment by xinbenlv** [comment]
This is the revision you published: https://en.wikipedia.org/w/index.php?title=Storming_of_the_Bastille&oldid=956088587, which is under your user name Jurbop

**Comment by xinbenlv** [comment]
Assigning back to doplu@ for verification

**Comment by doplu** [comment]
Yes it is the revision :  https://en.wikipedia.org/w/index.php?title=Storming_of_the_Bastille&oldid=956088587
Please note as you can see in the video that I copied pasted (sorry by habit! ) the second part of the comment _"Identified as test/vandalism using m:WikiLoop Battlefield version 4.0.1-beta. See it or provide your opinion at http://battlefield.wikiloop.org/revision/enwiki/956088406). "_ like that people know about wikiloop battefield !

**Comment by xinbenlv** [comment]
Thanks for reporting. You are right, there is a problem I can replicate.

**Comment by xinbenlv** [comment]
The fix will be implemented with #225
