### ISSUE TITLE
Remove cookie “io” since it's not being used.

### ISSUE THREAD

**Issue by bhavyakaria** [google/wikiloop-battlefield#239]
According to the latest Chrome update, a cookie with SameSite=None requires a secure attribute, or else it will be rejected.

**Reference**
https://www.chromestatus.com/feature/5633521622188032

**Solution**
And according to [this](https://github.com/socketio/socket.io/issues/2276) issue on [socket.io](https://github.com/socketio/socket.io/), the cookie "io" is not being used and can be removed.

**Screenshots**
![SS1](https://i.imgur.com/ORILPsA.png)

![SS2](https://i.imgur.com/siGs1fj.png)

**Comment by xinbenlv** [comment]
I am not super familiar with socket.io and it's implication of using cookie. If this fall into your domain expertise, I would greatly appreciate a PR

**Comment by bhavyakaria** [comment]
Working on it @xinbenlv

**Comment by xinbenlv** [comment]
While you are at it, i noticed you are also a graphic designer, if you are interested, we need design contributions too, as you can see the visual and UX is not my domain expertise. :)

**Comment by bhavyakaria** [comment]
Not an expert but would love to give it a try @xinbenlv.
