### ISSUE TITLE
Login functionality doesn't work on local

### ISSUE THREAD

**Issue by bhavyakaria** [google/wikiloop-battlefield#242]
Not able to log in when developing locally. 

Getting 404 on the following API,
http://localhost:3000/auth/mediawiki/login

**Checked Developers page of MediaWiki and found this**
> callback URL: the URL where the user returns after authorization is checked against this. (This is an extra layer of security against an attacker trying to steal credentials during authorization.) If the "use as prefix" option is enabled, the URL must start with this (the check is dumb so make sure to add at least a / after the domain name), otherwise it must be an exact match. If you are developing/testing your local machine, specify Localhost in this field (e.g. http://localhost:8080/).

**Reference**
https://www.mediawiki.org/wiki/OAuth/For_Developers#Authorization

**Comment by xinbenlv** [comment]
That's right, you will need to generate a local Oauth key and secret, or you can use this

```
MEDIAWIKI_CONSUMER_KEY=63edb156c538d3328d5aca509937472c
MEDIAWIKI_CONSUMER_SECRET=bffa02467d2170f90701c9c7e5bd7e2e46c33457
```

(Please if this make this credential public, it's only for local testing so if people start to abuse it we can ban it and apply for a new one.)

**Comment by xinbenlv** [comment]
Assigning to bhavyakaria@ for verification

**Comment by bhavyakaria** [comment]
@xinbenlv still getting 404 on using the above credentials. Had added them in the .env file.

**Comment by xinbenlv** [comment]
could you record video？

**Comment by bhavyakaria** [comment]
@xinbenlv Have sent you the recorded video on Discord.

**Comment by xinbenlv** [comment]
Awesome, it's evening here today I will try to take a look tomorrow. Please allow me for another day for response. In the meanwhile, I guess you could develop without the Oauth as a anonymous, right?

**Comment by bhavyakaria** [comment]
No issues. Yes, currently I'm able to develop with Anonymous.

**Comment by xinbenlv** [comment]
I am able to replicate it on my local. I will work on it.
