### ISSUE TITLE
B: Setting undefined for ORES Damaging & Badfaith score

### ISSUE THREAD

**Issue by bhavyakaria** [google/wikiloop-battlefield#250]
On clicking either of the scores, ORES Damaging and ORES Badfaith lead to Bad Request.

What is the desired behavior here and what values should be set to them so that it points to valid URL.

**Screenshot**
![IMG](https://i.imgur.com/kv00uUn.png)

**Comment by xinbenlv** [comment]
RevIds should point to the revId (in this case, something like 958021924).
This is due to a change of schema we rely on. Do you want to try to fix it?

**Comment by bhavyakaria** [comment]
Yes, @xinbenlv. Will take it after completing the current tasks.
