### ISSUE TITLE
Extraneous } after (empty) in edit summary field

### ISSUE THREAD

**Issue by sohomdatta1** [google/wikiloop-battlefield#269]
When there is no edit summary for a particular diff, while evaluating the diff the `Edit Summary:` field displays the following message `(empty)}` this should be changed to `(empty)` :)

**Comment by dominguetigs** [comment]
A doubt. How the problem was adjusted. Couldn't we close this issue for a better organization?

**Comment by sohomdatta1** [comment]
Sure :) We should close this issue.

**Comment by xinbenlv** [comment]
You guys are right~
