### ISSUE TITLE
B: Handle consecutive vandalisms on the same Article. (Solution 1)

### ISSUE THREAD

**Issue by Grahamwp** [google/wikiloop-battlefield#57]
Original Subject: WikiLoop Battlefield  only partially reverts in cases of consecutive vandalism edits done by the same user

The subject line says it all. I think this is a major issue due to misleading edit summaries, and this project should be disabled until it is fixed. See [this page history](https://en.wikipedia.org/w/index.php?title=Federation_of_Australia&offset=&limit=5&action=history). I also brought this up [on Meta](https://meta.wikimedia.org/wiki/Talk:WikiProject_WikiLoop#WikiLoop_Battlefield), along with another minor issue.

**Comment by xinbenlv** [comment]
Hi @Grahamwp thanks for your report of issue. Per your request, I currently disable revert. Let's have follow up discussion about how we can resolve this problem.

**Comment by xinbenlv** [comment]
**Solution 1**: When a revision is marked as `ShouldRevert`, also check if a previous revision is from the same user, if it comes from the same user, instead of going to the revert shortcut link, we let people go to the article history of the title.

**Comment by Grahamwp** [comment]
Thanks for disabling the edit functionality for now. What I was thinking was more broadly in line with how other anti-vandalism tools work. Go to the last revision not by the vandal, click on the edit link there (so you're editing that revision), and put in the edit summary something like "Reverting to last version by [name of previous user] ... [program string]". In the Federation of Australia example, you'd go here:
https://en.wikipedia.org/w/index.php?title=Federation_of_Australia&action=edit&oldid=908842179

Ideally this revert would be automated using OAuth or something to establish a user's credentials, for efficiency, like other anti-vandalism tools. Also, ideally the vandalism tool should warn the user using {{subst:uw-vandalism[n]}} ~~~~, where n is from 1  to 4, and then report the user for vandalism at the [Administrator intervention against vandalism](https://en.wikipedia.org/wiki/Wikipedia:Administrator_intervention_against_vandalism) page.

I think you should really have a go at some anti-vandalism tools yourself and maybe dive into their code to see how they operate. The most popular are both open-source ... [Twinkle](https://en.wikipedia.org/wiki/Wikipedia:Twinkle) and, for what I'm told is vandalism-fighting on steroids, [Huggle](https://en.wikipedia.org/wiki/Wikipedia:Huggle). Their talk pages might help you find other users willing to advise you. I've actually never done RecentChanges patrolling in my life (I have enough problems with my watchlist!), and my only modern programming experience is enough Python to be dangerous. I've just been on Wikipedia for a really, really long time and have experienced a lot of things on the site.

**Comment by xinbenlv** [comment]
This is fixed by 0e5c6ec commit.
We render the solution 1 for now.

We are going to create a second solution that more integrated with MediaWiki, but will require #61

**Comment by xinbenlv** [comment]
Close for Solution 1. For Solution 2 that involves comprehensive login-integration and permission application, we will do it in a separate Feature Request: #65
