### ISSUE TITLE
B: package-lock.json is out of sync with package.json

### ISSUE THREAD

**Issue by kenrick95** [google/wikiloop-battlefield#58]
After freshly cloning this repository, I run the command [`npm ci`](https://docs.npmjs.com/cli/ci) to cleanly install packages as specified in package-lock.json, but it failed because package.json and package-lock.json are "not in sync".

The full error log are:

```
npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR!
npm ERR!
npm ERR! Missing: @dicebear/avatars@^3.1.3
npm ERR! Missing: @dicebear/avatars-male-sprites@^2.1.3
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     [redacted]\npm-cache\_logs\2019-08-04T15_00_02_922Z-debug.log
```

To fix this, I run `npm install` command, and indeed the package-lock.json file is updated. Please update package-lock.json. (I can send a PR if you don't mind 😁)

Thanks

**Comment by xinbenlv** [comment]
Thank you for reporting. I will address this soon
