### ISSUE TITLE
FR: Readme: template.env not provided?

### ISSUE THREAD

**Issue by kenrick95** [google/wikiloop-battlefield#59]
The readme file has the following statement:

> A template has been provided in the `template.env`. Once set, you should do `cp template.env .env` to create such file in the exact name.

but I cannot find any `template.env` file in the latest master branch, only a `heroku.env`, which I don't think is the correct file.

Please help to provide a `template.env` file, or correct the readme file.

Thanks

**Comment by xinbenlv** [comment]
Thank you for reporting. I will address this soon

**Comment by xinbenlv** [comment]
Hi @kenrick95  you should now be able to deploy to heroku directly. We also include a `template.env` FYI. Let me know if this resolves your question

**Comment by kenrick95** [comment]
Thank you!
