### ISSUE TITLE
Add instructions for setting up mongodb - dev setup

### ISSUE THREAD

**Issue by epicfaace** [google/wikiloop-battlefield#73]

**Comment by xinbenlv** [comment]
If you click on "Deploy-to-Heroku" button it will generate a Heroku instance ([which comes with a mongodb addon](https://github.com/google/wikiloop-battlefield/blob/920c720f3b60dd705f2bb2a229f04e5a14596b63/app.json#L7), and through that you can get a mongodb instance)

**Comment by xinbenlv** [comment]
Done
