### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by epicfaace** [google/wikiloop-battlefield#74]
This happens when cloning the repo fresh and trying to run.

![image](https://user-images.githubusercontent.com/1689183/63628795-5660f480-c5c3-11e9-9382-bb5ac522d2eb.png)

**Comment by xinbenlv** [comment]
If you are developing in local, remember to create a `.env` file. See [template.env](https://github.com/google/wikiloop-battlefield/blob/master/template.env)

**Comment by epicfaace** [comment]
Yeah, I did that. It appears that this happened because some environment variables were not included by default in `heroku.env`. I've made a PR to add that env variable in.

**Comment by xinbenlv** [comment]
> Yeah, I did that. It appears that this happened because some environment variables were not included by default in heroku.env. I've made a PR to add that env variable in.

Cool
